# Generated by Django 2.2.dev20180807001522 on 2018-10-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_credentialsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='client_secret',
        ),
    ]
